owner: ivancarlos-me
repo: Uptime-by-GitHub
user-agent: ivancarlos-me

sites:
  - name: UptimeRobot
    url: https://uptimerobot.com
  - name: Punto.alerta
    url: https://alerta.org.br
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: SP4.sp4com
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: SP4.sp4comunicacao
    url: https://sp4comunicacao.com.br
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: iccsv05
    url: iccsv05.ivancarlos.com.br
    port: 443
    check: "tcp-ping"

status-website:
  theme: night
  cname: monitor2.ivancarlos.com.br
  logoUrl: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/BNCnMqeS.png
  name: "Monitor2 de Status: Uptime by GitHub"
  introTitle: "**Monitor2 de Status: Uptime by GitHub** is our secondary monitoring tool powered entirely by GitHub."
  introMessage: This is the monitor status page which uses **real-time** data from our [**GitHub repository**](https://github.com/ivancarlos-me/Uptime-by-GitHub). No server required, just GitHub Actions, Issues, and Pages.
  favicon: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/7vqI6o13.png
  #faviconSvg: https://example.com/logo.svg
  customHeadHtml: "<!-- -->"
  customBodyHtml: "<!-- -->"
  js: "document.addEventListener('DOMContentLoaded',function(){var senha='ivancarlosconsultoria';var senhaDigitada=prompt('This status page is password protected.');if(senhaDigitada!==senha){alert('Access denied.');document.body.innerHTML='';window.location.href='https://monitor2.ivancarlos.com.br';}});"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Consultoria
      href: https://ivancarlos.com.br/
    - title: Links
      href: https://ivancarlos.me/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
