owner: ivancarlos-me
repo: Uptime-by-GitHub
user-agent: ivancarlos-me

sites:
  - name: UptimeRobot
    url: https://uptimerobot.com
    expectedStatusCodes:
      - 200
      
  - name: Punto.alerta
    url: https://alerta.org.br
    expectedStatusCodes:
      - 200
  - name: SP4.sp4com
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: SP4.sp4comunicacao
    url: https://sp4comunicacao.com.br/en
    expectedStatusCodes:
      - 200
      
  - name: Bowler.Bowlersv01.v6
    check: "tcp-ping"
    url: bowlersv01.bowler.com.br
    port: 80
    ipv6: true
      
  - name: Punto.puntosv09.v6
    check: "tcp-ping"
    url: puntosv09.puntocomunicacao.com.br
    port: 80
    ipv6: true
  - name: Punto.oxfamsv01.v6
    check: "tcp-ping"
    url: oxfamsv01.oxfam.org.br
    port: 80
    ipv6: true
  
  - name: FBSP.fbspsv01.v6
    check: "tcp-ping"
    url: fbspsv01.forumseguranca.org.br
    port: 80
    ipv6: true 
  - name: FBSP.fbspsv02.v6
    check: "tcp-ping"
    url: fbspsv02.forumseguranca.org.br
    port: 80
    ipv6: true
  - name: FBSP.fbspsv03.v6
    check: "tcp-ping"
    url: fbspsv03.forumseguranca.org.br
    port: 80
    ipv6: true
  - name: FBSP.fbspsv04.v6
    check: "tcp-ping"
    url: fbspsv04.forumseguranca.org.br
    port: 80
    ipv6: true 
  - name: FBSP.fbspsv05.v6
    check: "tcp-ping"
    url: fbspsv05.forumseguranca.org.br
    port: 80
    ipv6: true
    
  - name: ICC.iccsv01.v6
    check: "tcp-ping"
    url: iccsv01.ivancarlos.com.br
    port: 80
    ipv6: true
  - name: ICC.iccsv02.v6
    check: "tcp-ping"
    url: iccsv02.ivancarlos.com.br
    port: 80
    ipv6: true
  - name: ICC.iccsv03.v6
    check: "tcp-ping"
    url: iccsv03.ivancarlos.com.br
    port: 80
    ipv6: true
  - name: ICC.iccsv04.v6
    check: "tcp-ping"
    url: iccsv04.ivancarlos.com.br
    port: 80
    ipv6: true
  - name: ICC.iccsv05.v6
    check: "tcp-ping"
    url: iccsv05.ivancarlos.com.br
    port: 80
    ipv6: true
  - name: ICC.iccsv06.v6
    check: "tcp-ping"
    url: iccsv06.ivancarlos.com.br
    port: 80
    ipv6: true
    
status-website:
  themeUrl: https://monitor2.ivancarlos.com.br/icc.css
  cname: monitor2.ivancarlos.com.br
  logoUrl: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/BNCnMqeS.png
  name: "Monitor2 de Status"
  introTitle: "**Monitor2 de Status** is the secondary monitoring tool used by [**ICC**](https://ivancarlos.com.br) and hosted by [**GitHub**](https://github.com/)."
  introMessage: This monitor checks websites on hosting providers that blocks [**UptimeRobot**](https://icc.gg/uptimerobot), also checks control panels, dashboards~~, [IPv6 reachability](https://github.com/ivancarlos-me/Uptime-by-GitHub/issues/21#issuecomment-2381086861)~~.
  favicon: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/7vqI6o13.png
  faviconSvg: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/hGlsQKtB.svg
  customHeadHtml: "<!-- Google tag (gtag.js) --><script async src='https://www.googletagmanager.com/gtag/js?id=G-39VX59T3FR'></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-39VX59T3FR');</script>"
  customBodyHtml: "<!-- -->"
  js: "document.addEventListener('DOMContentLoaded',function(){var senha='ivancarlosconsultoria';var senhaDigitada=prompt('This status page is password protected.');if(senhaDigitada!==senha){alert('Access denied.');document.body.innerHTML='';window.location.href='https://monitor2.ivancarlos.com.br';}});document.addEventListener('contextmenu', event => event.preventDefault());"
  navbar:
    - title: ICC
      href: https://ivancarlos.com.br/
