owner: ivancarlos-me
repo: Uptime-by-GitHub

sites:
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#    maxResponseTime: 5000
  - name: UptimeRobot
    url: https://uptimerobot.com
  - name: Punto | Website | alerta.org.br
    url: https://alerta.org.br
    expectedStatusCodes:
      - 200
  - name: SP4 | Forwarder | sp4com.com.br
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 301
  - name: SP4 | Website | www.sp4comunicacao.com.br
    url: https://www.sp4comunicacao.com.br
    expectedStatusCodes:
      - 200
      - 302
#  - name: iccsv01
#    url: https://iccsv01.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true
#  - name: iccsv02
#    url: https://iccsv02.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true
#  - name: iccsv03
#    url: https://iccsv03.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true
#  - name: iccsv04
#    url: https://iccsv04.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true
#  - name: iccsv05
#    url: https://iccsv05.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true
#  - name: iccsv06
#    url: https://iccsv06.ivancarlos.com.br
#    port: 443
#    check: "tcp-ping"
#    ipv6: true

status-website:
  theme: ocean
  cname: monitor2.ivancarlos.com.br
  logoUrl: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/BNCnMqeS.png
  name: Uptime by GitHub
  introTitle: "**Uptime by GitHub** is the support monitoring tool to UptimeRobot, powered entirely by GitHub."
  introMessage: This is the monitor status page which uses **real-time** data from our [GitHub repository](https://github.com/ivancarlos-me/Uptime-by-GitHub). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  favicon: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/7vqI6o13.png
  #faviconSvg: https://example.com/logo.svg
  customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Links
      href: https://ivancarlos.me/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
