owner: ivancarlos-me
repo: Uptime-by-GitHub

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: UptimeRobot
    url: https://uptimerobot.com
    maxResponseTime: 5000
  - name: iccsv01
    url: https://iccsv01.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: iccsv02
    url: https://iccsv02.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: iccsv03
    url: https://iccsv03.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: iccsv04
    url: https://iccsv04.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: iccsv05
    url: https://iccsv05.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: iccsv06
    url: https://iccsv06.ivancarlos.com.br
    port: 443
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: monitor2.ivancarlos.com.br
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime by GitHub
  introTitle: "**Uptime by GitHub** is the support monitoring tool to UptimeRobot, powered entirely by GitHub."
  introMessage: This is the monitor status page which uses **real-time** data from our [GitHub repository](https://github.com/ivancarlos-me/Uptime-by-GitHub). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
