owner: ivancarlos-me
repo: Uptime-by-GitHub
user-agent: ivancarlos-me

sites:
  - name: UptimeRobot
    url: https://uptimerobot.com
    expectedStatusCodes:
      - 200
      
  - name: Punto.alerta
    url: https://alerta.org.br
    expectedStatusCodes:
      - 200
  - name: SP4.sp4com
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: SP4.sp4comunicacao
    url: https://sp4comunicacao.com.br/en
    expectedStatusCodes:
      - 200
      
  - name: Bowler.bowlersv01.cp
    url: https://bowlersv01.bowler.com.br

  - name: Punto.puntosv01.cp
    url: https://puntosv01.puntocomunicacao.com.br
  - name: Punto.puntosv06.cp
    url: https://puntosv06.puntocomunicacao.com.br
  - name: Punto.puntosv07.cp
    url: https://puntosv07.puntocomunicacao.com.br
  - name: Punto.puntosv08.cp
    url: https://puntosv08.puntocomunicacao.com.br
  - name: Punto.puntosv09.cp
    url: https://puntosv09.puntocomunicacao.com.br
  - name: Punto.puntosv10.cp
    url: https://puntosv10.puntocomunicacao.com.br
  - name: Punto.oxfamsv01.cp
    url: https://oxfamsv01.oxfam.org.br
  - name: Punto.oxfamsv02.cp
    url: https://oxfamsv02.oxfam.org.br

  - name: FBSP.fbspsv01.cp
    url: https://fbspsv01.forumseguranca.org.br
  - name: FBSP.fbspsv02.cp
    url: https://fbspsv02.forumseguranca.org.br
  - name: FBSP.fbspsv03.cp
    url: https://fbspsv03.forumseguranca.org.br
  - name: FBSP.fbspsv04.cp
    url: https://fbspsv04.forumseguranca.org.br
  - name: FBSP.fbspsv05.cp
    url: https://fbspsv05.forumseguranca.org.br
    
  - name: ICC.iccsv01.cp
    url: https://iccsv01.ivancarlos.com.br
  - name: ICC.iccsv02.cp
    url: https://iccsv02.ivancarlos.com.br
  - name: ICC.iccsv03.cp
    url: https://iccsv03.ivancarlos.com.br
  - name: ICC.iccsv04.cp
    url: https://iccsv04.ivancarlos.com.br
  - name: ICC.iccsv05.cp
    url: https://iccsv05.ivancarlos.com.br
  - name: ICC.iccsv06.cp
    url: https://iccsv06.ivancarlos.com.br
    
status-website:
  theme: ocean
  css: body { -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; -o-user-select: none; user-select: none; }
  cname: monitor2.ivancarlos.com.br
  logourl: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/BNCnMqeS.png
  name: "Monitor2 de Status"
  introTitle: "**Monitor2 de Status** is the secondary monitoring tool used by [**ICC**](https://ivancarlos.com.br) and hosted by [**GitHub**](https://github.com/)."
  introMessage: This monitor checks websites on hosting providers that blocks [**UptimeRobot**](https://icc.gg/uptimerobot), also checks control panels, dashboards, IPv6 reachability.
  favicon: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/7vqI6o13.png
  faviconSvg: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/hGlsQKtB.svg
  customHeadHtml: "<!-- Google tag (gtag.js) --><script async src='https://www.googletagmanager.com/gtag/js?id=G-39VX59T3FR'></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-39VX59T3FR');</script>"
  customBodyHtml: "<!-- -->"
  js: "document.addEventListener('DOMContentLoaded',function(){var senha='ivancarlosconsultoria';var senhaDigitada=prompt('This status page is password protected.');if(senhaDigitada!==senha){alert('Access denied.');document.body.innerHTML='';window.location.href='https://monitor2.ivancarlos.com.br';}});document.addEventListener('contextmenu', event => event.preventDefault());"
  navbar:
    - title: ICC
      href: https://ivancarlos.com.br/
